@InventoryDashboard.WebApi_HostAddress = http://localhost:5000

GET {{InventoryDashboard.WebApi_HostAddress}}/api/stocks
Accept: application/json

###

POST {{InventoryDashboard.WebApi_HostAddress}}/api/stocks
Content-Type: application/json

{
  "symbol": "IBM",
  "company": "IBM",
  "price": 172.45,
  "shares": 90
}

###

POST {{InventoryDashboard.WebApi_HostAddress}}/api/stocks/simulate
Accept: application/json

###
